# Exercie 2

In [1]:
import numpy as np
import pandas as pd

flippers_raw = pd.read_csv('../../data/flipper_games.csv')
flippers_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 5409 entries, 0 to 5408
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         5409 non-null   str
 1   player_id         5409 non-null   str
 2   machine_id        5409 non-null   str
 3   machine_type      5409 non-null   str
 4   arcade_zone       5409 non-null   str
 5   game_mode         5409 non-null   str
 6   game_duration_s   5409 non-null   int64
 7   pause_s           5409 non-null   int64
 8   tilt_risk_pct     5409 non-null   float64
 9   ball_speed_mps    5409 non-null   float64
 10  playfield_temp_c  5409 non-null   float64
 11  error_code        279 non-null    str
 12  game_status       5409 non-null   str
 13  incident_label    5409 non-null   int64
dtypes: float64(3), int64(3), str(8)
memory usage: 591.7 KB

---
## Suppression des doublons

In [7]:
f_no_dup = flippers_raw.drop_duplicates()
f_no_dup

,timestamp,player_id,machine_id,machine_type,arcade_zone,game_mode,game_duration_s,pause_s,tilt_risk_pct,ball_speed_mps,playfield_temp_c,error_code,game_status,incident_label
0,2026-02-03 10:00:00,P001,F17,electromechanical,C3,speedrun,188,0,39.32,1.154,37.76,NaN,completed,0
1,2026-02-03 10:00:00,P221,F04,solid_state,D1,multiball,218,23,76.10,1.002,30.84,NaN,completed,0
2,2026-02-03 10:05:00,P034,F13,digital,C1,classic,143,21,5.86,0.965,33.96,NaN,completed,0
3,2026-02-03 10:05:00,P007,F06,solid_state,D1,multiball,319,41,47.16,1.054,28.43,NaN,completed,0
4,2026-02-03 10:05:00,P009,F16,electromechanical,A2,classic,175,33,60.06,0.934,22.61,NaN,completed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5404,2026-02-12 21:20:00,P077,F11,digital,D1,classic,166,40,61.93,1.376,30.34,NaN,completed,0
5405,2026-02-12 21:25:00,P180,F15,electromechanical,C2,speedrun,168,21,66.50,1.109,31.17,NaN,completed,0
5406,2026-02-12 21:25:00,P228,F03,solid_state,A2,multiball,310,1,64.41,1.124,28.49,NaN,completed,0
5407,2026-02-12 21:25:00,P213,F01,solid_state,C3,speedrun,168,29,22.25,0.810,25.05,NaN,completed,0
5408,2026-02-12 21:30:00,P004,F13,digital,A1,multiball,-191,16,37.33,1.089,30.77,NaN,completed,0

---
## On conserve les parties avec ```game_duration_s>0```

In [9]:
f_game_duration = (f_no_dup[f_no_dup['game_duration_s']>0])
f_game_duration

,timestamp,player_id,machine_id,machine_type,arcade_zone,game_mode,game_duration_s,pause_s,tilt_risk_pct,ball_speed_mps,playfield_temp_c,error_code,game_status,incident_label
0,2026-02-03 10:00:00,P001,F17,electromechanical,C3,speedrun,188,0,39.32,1.154,37.76,NaN,completed,0
1,2026-02-03 10:00:00,P221,F04,solid_state,D1,multiball,218,23,76.10,1.002,30.84,NaN,completed,0
2,2026-02-03 10:05:00,P034,F13,digital,C1,classic,143,21,5.86,0.965,33.96,NaN,completed,0
3,2026-02-03 10:05:00,P007,F06,solid_state,D1,multiball,319,41,47.16,1.054,28.43,NaN,completed,0
4,2026-02-03 10:05:00,P009,F16,electromechanical,A2,classic,175,33,60.06,0.934,22.61,NaN,completed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5403,2026-02-12 21:20:00,P196,F20,electromechanical,C3,multiball,392,33,29.62,1.604,36.07,NaN,completed,0
5404,2026-02-12 21:20:00,P077,F11,digital,D1,classic,166,40,61.93,1.376,30.34,NaN,completed,0
5405,2026-02-12 21:25:00,P180,F15,electromechanical,C2,speedrun,168,21,66.50,1.109,31.17,NaN,completed,0
5406,2026-02-12 21:25:00,P228,F03,solid_state,A2,multiball,310,1,64.41,1.124,28.49,NaN,completed,0
5407,2026-02-12 21:25:00,P213,F01,solid_state,C3,speedrun,168,29,22.25,0.810,25.05,NaN,completed,0

## On conserve les lignes avec ```0<tilt_risk_pct<100```

In [11]:
type(f_game_duration)

pandas.DataFrame

In [12]:
f_tilt_risk=f_game_duration[f_game_duration["tilt_risk_pct"].between(0,100)]
f_tilt_risk

,timestamp,player_id,machine_id,machine_type,arcade_zone,game_mode,game_duration_s,pause_s,tilt_risk_pct,ball_speed_mps,playfield_temp_c,error_code,game_status,incident_label
0,2026-02-03 10:00:00,P001,F17,electromechanical,C3,speedrun,188,0,39.32,1.154,37.76,NaN,completed,0
1,2026-02-03 10:00:00,P221,F04,solid_state,D1,multiball,218,23,76.10,1.002,30.84,NaN,completed,0
2,2026-02-03 10:05:00,P034,F13,digital,C1,classic,143,21,5.86,0.965,33.96,NaN,completed,0
3,2026-02-03 10:05:00,P007,F06,solid_state,D1,multiball,319,41,47.16,1.054,28.43,NaN,completed,0
4,2026-02-03 10:05:00,P009,F16,electromechanical,A2,classic,175,33,60.06,0.934,22.61,NaN,completed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5403,2026-02-12 21:20:00,P196,F20,electromechanical,C3,multiball,392,33,29.62,1.604,36.07,NaN,completed,0
5404,2026-02-12 21:20:00,P077,F11,digital,D1,classic,166,40,61.93,1.376,30.34,NaN,completed,0
5405,2026-02-12 21:25:00,P180,F15,electromechanical,C2,speedrun,168,21,66.50,1.109,31.17,NaN,completed,0
5406,2026-02-12 21:25:00,P228,F03,solid_state,A2,multiball,310,1,64.41,1.124,28.49,NaN,completed,0
5407,2026-02-12 21:25:00,P213,F01,solid_state,C3,speedrun,168,29,22.25,0.810,25.05,NaN,completed,0

---
## On conserve les ligne avec ```pause_s >= 0````

In [23]:
f_clean=f_tilt_risk[f_tilt_risk["pause_s"]>=0]
f_clean

,timestamp,player_id,machine_id,machine_type,arcade_zone,game_mode,game_duration_s,pause_s,tilt_risk_pct,ball_speed_mps,playfield_temp_c,error_code,game_status,incident_label
0,2026-02-03 10:00:00,P001,F17,electromechanical,C3,speedrun,188,0,39.32,1.154,37.76,NaN,completed,0
1,2026-02-03 10:00:00,P221,F04,solid_state,D1,multiball,218,23,76.10,1.002,30.84,NaN,completed,0
2,2026-02-03 10:05:00,P034,F13,digital,C1,classic,143,21,5.86,0.965,33.96,NaN,completed,0
3,2026-02-03 10:05:00,P007,F06,solid_state,D1,multiball,319,41,47.16,1.054,28.43,NaN,completed,0
4,2026-02-03 10:05:00,P009,F16,electromechanical,A2,classic,175,33,60.06,0.934,22.61,NaN,completed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5403,2026-02-12 21:20:00,P196,F20,electromechanical,C3,multiball,392,33,29.62,1.604,36.07,NaN,completed,0
5404,2026-02-12 21:20:00,P077,F11,digital,D1,classic,166,40,61.93,1.376,30.34,NaN,completed,0
5405,2026-02-12 21:25:00,P180,F15,electromechanical,C2,speedrun,168,21,66.50,1.109,31.17,NaN,completed,0
5406,2026-02-12 21:25:00,P228,F03,solid_state,A2,multiball,310,1,64.41,1.124,28.49,NaN,completed,0
5407,2026-02-12 21:25:00,P213,F01,solid_state,C3,speedrun,168,29,22.25,0.810,25.05,NaN,completed,0

---
## Vérification du nombre de lignes

In [25]:
before=flippers_raw.shape[0]
after=f_clean.shape[0]
print("before: ", before,"lignes")
print("After: ", after, "lignes")
print("Nombre de lignes retirées: ", (before - after))

before:  5409 lignes
After:  5354 lignes
Nombre de lignes retirées:  55